### ISSUE TITLE
CovFinder `beta_gprior_std` accept vector rather than only a scalar

### ISSUE THREAD

**Issue by zhengp0** [ihmeuw-msca/MRTool#62]

**Comment by zhengp0** [comment]
Did a little more digging. This parameter is used as a ridge regression in the covariate selection process. It applies to both the initial `pre_selected_cov` model, and later on the added covariate. So I think the scalar actually makes sense. In BoP, we can stick with the mean approach or if we want to be more aggressive we can do `min` as well. @n-gilbertson let me know what you think, and we can discuss it when we meet :)

**Comment by n-gilbertson** [comment]
Sounds good, @zhengp0, thanks! Happy to chat about whether to use the mean or min approach for BoP when we meet next.

**Comment by zhengp0** [comment]
Thanks very much!
